### ISSUE TITLE
Add shell completions

### ISSUE THREAD

**Issue by workflow** [tenx-tech/rmob#32]
@ebkalderon commented: 

> Maybe we could later add a subcommand that generates Bash, ZSH, and Fish completions so users don't have to worry about typing? See [`App::gen_completions_to()`](https://docs.rs/clap/2.33.0/clap/struct.App.html#method.gen_completions_to) and an example use [here](https://github.com/ebkalderon/deck/blob/master/deck/src/commands/completion.rs#L49-L50).

**Comment by ebkalderon** [comment]
Also, the `clap()` method seen in the example use posted above comes from [`StructOpt::clap()`](https://docs.rs/structopt/0.3.2/structopt/trait.StructOpt.html#tymethod.clap), which returns an `App` that we can call `gen_completions_to()`. This `clap()` method is available on any struct that derives `StructOpt`.
